[config]
loglevel = true

[[database]]
name = "pg"
kind = "postgres"
host = "51.89.149.155"
port = 5432
username = "postgres"
password = "number1nonce"
database = "postgres"

[[database]]
name = "mysql"
kind = "mysql"
host = "198.244.176.33"
port = 6033
username = "Ciska_ext_test"
password = "Ra6evum52obay3tEK73oRuweHOSAdE"
database = "maldenlife_dev"